### ISSUE TITLE
Inverse Design Gradient not being calculated for etched structures properly 

### ISSUE THREAD

**Issue by LukeVance5** [flexcompute/tidy3d#1865] opened 2024-07-31 09:05 UTC
@yorickreum

When creating etched structures by creating JaxPolySlabs with permmitivity of 1,
The gradient for that structure is zero

Solution:

Set the permittivity to slightly above 1

Example:

Example Code of etched chirped bullseye (Modifed version of particle swarm to allow adjoint)
Bullseye geometry initialization

![1](https://github.com/user-attachments/assets/e6e207d8-3a64-437b-9280-9b17bba07bb5)

Helper Function

![grafik](https://github.com/user-attachments/assets/80d03d8b-01a4-43eb-9957-1dc794e77228)

When mat_etch permittivity = 1.0

![grafik](https://github.com/user-attachments/assets/7798d94c-2446-40eb-805d-d1969c088bb1)

![grafik](https://github.com/user-attachments/assets/44bb673d-f56a-4617-afa1-e90d0a3db132)

Parmeters here are radius of cavity, period, and width

When mat_etch permittivity = 1.0001

![grafik](https://github.com/user-attachments/assets/cd9305d7-1653-4d24-ac56-2a102856831a)

![grafik](https://github.com/user-attachments/assets/69c89610-e0a7-4cfd-837f-8ae988961109)

**Comment by yaugenst-flex** [comment] 2024-07-31 09:52
Closing as duplicate of #1864

**Closed as completed by yaugenst-flex** 2024-07-31 09:52 UTC
