### ISSUE TITLE
Future `python==3.12` compatibility.

### ISSUE THREAD

**Issue by daquinteroflex** [flexcompute/tidy3d#1317] opened 2023-12-15 10:48 UTC
Just thought to write a list of depreciated commands we need to update throughout the frontend

- [X] All the `typing.List`, `typing.Tuple`, etc. need to be updated to standard `list`, `tuple` type declarations. UPDATE: turns out they're only depreciating them from development, but still mantain backward compatibility. I thought I had read they were being depreciated, but I guess I misunderstood this as not supported. I think they will support it for backward compatibility until they choose t[o remove them ](https://docs.python.org/3/library/typing.html#deprecation-timeline-of-major-features).
- [X] jax updates
- [x] `gdstk` update for 3.12 windows support? re https://github.com/heitzmann/gdstk/issues/228. Actions issue can be partly linked to [this](https://github.com/python-poetry/poetry/issues/5599). Possibly we need [this](https://github.com/python-poetry/poetry/pull/9150) to be propagated along in our poetry config to force a specific installation.
- [x] We know `trimesh` ->  `rtree` are [not bundling unlike previous versions](https://github.com/geometries/trimesh_upstream?tab=readme-ov-file#current-status) `libspatialindex`. Need to decide what to do about this. rtree files are [here](https://pypi.org/project/Rtree/#files) and [libspatialindex](https://libspatialindex.org/en/latest/index.html) is here. Fixed by updating rtree in the dependencies.

We can work around:
- [x] poetry issues on pandas 3.9 wheels on their latest release https://github.com/pandas-dev/pandas/issues/58289

Poetry issues we might have:
- Related to [binary installs](https://github.com/python-poetry/poetry/issues/6798). Sorted by manually installing onto the venv via pip poetry 1.9 releases only-binary

**Comment by tylerflex** [comment] 2024-01-05 14:54
hm, so I guess python 3.12 is already out since October? are we behind in not supporting it yet?

If we change `typing.Tuple` -> `tuple` will that affect our package when running older versions of python?

**Comment by momchil-flex** [comment] 2024-01-05 18:17
I'm pretty sure it's OK already in 3.9 but I don't remember if 3.8 accepts those, maybe not.

We *could* drop 3.8 soon although probably a few users would prefer not yet. :)

**Comment by qt-thomas** [comment] 2024-04-16 19:54
I'd be happy if this was done sooner rather than later. My environment is at 3.12 and pip installs 2.5.2 by default, instead of 2.6.

**Comment by momchil-flex** [comment] 2024-04-16 22:06
It would be a good time to put this in our 2.7 pre-release. However it seems like our pinning of the jaxlib version is a problem (I guess that version doesn't work with python 3.12) https://github.com/flexcompute/tidy3d/actions/runs/8713087293/job/23900800212?pr=1620

Thoughts @tylerflex ?

**Comment by tylerflex** [comment] 2024-04-17 03:57
@momchil-flex I think the bigger issue is that all of the type annotations (eg. `typing.tuple` and `tuple`) would need to be compatible with all versions. Last I checked, it wasn't very simple. I think once we fix the jax issue we'll run into this. It's possible we can get it done for 2.7 official release, but definitely not rc1.

**Comment by momchil-flex** [comment] 2024-04-17 04:04
Yeah it won't be rc1. I see now we need to do these changes but I don't see what the problem is if we don't support 3.8 anymore. But I guess won't know until we try, but yeah let's definitely try for 2.7.

**Comment by daquinteroflex** [comment] 2024-04-17 07:26
Hi @qt-thomas, apologies for the delay on this! I'm working on it now and will try to get it done for you asap. I will comment here again whenever we've released it in pypi just so you know too.

**Comment by qt-thomas** [comment] 2024-04-17 10:56
I have installed it anyway with the ignore-python-requires. I will report
if I run into any issues.

**Comment by momchil-flex** [comment] 2024-04-19 19:57
Fixed in #1622 , to appear in 2.7.0rc1 release this Monday.

**Closed by momchil-flex** 2024-04-19 19:57 UTC
Labels: packaging, 2.7
