### ISSUE TITLE
numpy2 support

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1912] opened 2024-08-20 21:14 UTC
What's the plan for numpy2 support?

**Comment by yaugenst-flex** [comment] 2024-08-21 08:22
For the most part this is gated by numpy2 support from dependencies, the tidy3d frontend is already numpy2 compatible as far as I can tell (minus two `np.trapz` calls...). Are there any numpy2-specific features that you need?

**Comment by daquinteroflex** [comment] 2024-08-21 08:58
Hi Joaquin! Hope you're well.

So if the issue is a packaging/integration one with other packages that require/use 2.0, I'm opening a PR that will loosen the current pyproject.toml requirement. My understanding is the same as Yannick that we already are 2.0 compatible mostly limited by the dependencies on this. https://github.com/flexcompute/tidy3d/blob/53ef995c2ba6131cb9b5d721069c8061e8de3704/pyproject.toml#L31

Then just need to make sure tests pass and we'd release it in pypi the next release, either 2.7.3 or 2.8.0 in the next few weeks I believe. If there's anything feature-specific we can also look into that as Yannick mentions.

**Comment by momchil-flex** [comment] 2024-08-21 09:07
I know there was an autograd issue but it seems like they have merged [their numpy v2 PR](https://github.com/HIPS/autograd/pull/618). But yeah we just need to test everything.

**Comment by yaugenst** [comment] 2024-08-21 09:17
Note that we would need some logic to call `np.trapz` or `np.trapezoid` depending on numpy version.

**Comment by agriyakhetarpal** [comment] 2024-08-22 11:52
Hi there, thanks for the cross-link. We released a new version of Autograd: https://github.com/HIPS/autograd/releases/tag/v1.7.0, which includes NumPy v2 support through the above PR. It will be available via PyPI later in the day.

**Comment by jan-david-fischbach** [comment] 2024-11-14 12:55
Hey all,
any other roadblocks, that would need to be addressed? 

Regards JD

**Comment by yaugenst-flex** [comment] 2024-11-14 13:03
Hey @jan-david-fischbach, this is tracked in #1913 and will (probably?) make it into the next release. However I _think_ current develop should already be fine with numpy 2 (there was only a `np.trapz` call that was replaced), so if you are willing to install from develop and force upgrade numpy afterward it _might_ just work? No guarantees though 😬

**Closed as completed** 2024-11-19 13:55 UTC
