### ISSUE TITLE
database

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#725] opened 2023-02-27 00:06 UTC
How can we use a database to store simulation results?

Ideally we can work together on a schema that works both for simulation results and measurements

https://github.com/gdsfactory/gdsfactory/issues/992

**Comment by tylerflex** [comment] 2023-02-27 15:38
Hm, well the closest thing we could do within the current tidy3d framework is to have a dict mapping `Simulation` -> `SimulationData`. Someone wanting to look up the results of a `Simulation` would just use that simulation as a key into this dictionary and load the corresponding `SimulationData`. These both have a well-defined schema, which can be generated using eg. `Simulation.schema()` using pydantic's built in.

I'm not sure how this would be stored, practically. Right now the simulation data are stored most efficiently as `.hdf5` files so this "database" could actually map to the filename or group name of each SimulationData.

I assume what you'd eventually like to do, though, is to have a mapping of various simulation **parameters** to various post processing results (not necessarily `td.MonitorData` objects) so for this I feel like the easiest thing to do is wrap the tidy3d Simulation -> SimulationData in your own pre- and post- processing pipelines that eg. convert Simulations to parameters for storage in a database and post process SimulationData into measurables.

Sorry, I don't quite understand what youre envisioning here but if there's a specific feature / schema we can help with let us know.

**Comment by tylerflex** [comment] 2023-02-27 17:06
You're saying that, for example, if a `Simulation` is updated that has a hash identical to a simulation uploaded by the same (or any) user, the associated `SimulationData` is immediately returned? This could be interesting.

**Comment by tylerflex** [comment] 2023-02-27 17:09
I made an issue #728 for this as I think it would be a good thing for us to support natively anyway.

**Comment by joamatab** [comment] 2023-02-27 21:49
Yes, that avoids running the same simulation twice, which is a waste of resources

**Comment by tylerflex** [comment] 2023-07-03 10:06
closing as duplicate of #936

**Closed by tylerflex** 2023-07-03 10:06 UTC
Labels: feature
